[build-system]
requires = ["setuptools>=42", "pydantic"]
build-backend = "setuptools.build_meta"

[tool.black]
include = "(main|tests)/.*"

[tool.pycln]
extend-exclude = [".*/__init__.py"]

[tool.isort]
profile = "black"
skip_gitignore = "true"
src_paths = ["main", "tests"]